"""Shared stubs for the stats tests.

Everything here is duck-typed on purpose: the decoders read four attributes off
the resolved spec and three members off the maps object, so the tests do not
need a full RunSpec/ResolvedSpec construction to exercise them.

Fixture provenance (tests/fixtures/stats/)
------------------------------------------
None of the three was produced by the code it now tests -- a fixture generated by
its own decoder proves nothing. They are hand-written payloads whose SHAPE is read
off the legacy consumers, which were themselves written against live Earth Engine
responses, and whose VALUES were chosen to exercise the decoders' edges:

``transition_areas.json``
    One flat group list. ``run_15_3_1.py:240-242`` reads ``g["lc_comb"]`` and
    ``g["sum"]`` off it, so each entry is keyed by the ``groupName`` passed to
    ``Reducer.group`` (``"lc_comb"``, :227) plus the ``"sum"`` of ``Reducer.sum``.
    Values: five transition codes drawn from the default seven-class vocabulary --
    a class onto itself (1010, 2020, 7070) and both directions of one off-diagonal
    pair (1030, 3010), so a decoder that read the code backwards would swap two
    rows rather than produce the same frame.

``areas_by_land_cover.json``
    The nested form the two stacked ``Reducer.group``s of :274 produce, outer key
    from ``.group(2, "indicator")`` and inner from ``.group(1, "lc")``.
    ``run_15_3_1.py:291-295`` reads exactly ``i["indicator"]``, ``i["groups"]``,
    ``g["lc"]`` and ``g["sum"]``. Values: three indicator classes over three land
    cover codes, deliberately RAGGED (2, 1 and 2 inner entries) so a decoder that
    assumed a rectangular payload would not survive, and with land cover 10 absent
    from indicator 3 so the pivot has a genuinely missing cell to fill.

``zonal_features.json``
    A GeoJSON FeatureCollection exactly as ``FeatureCollection.getInfo()`` returns
    one (run_15_3_1.py:544). The ``Class_N`` property spelling comes from
    ``ee.Number(...).format("Class_%d")`` at :519 and is confirmed by both legacy
    readers, :557 (``c.startswith("Class_")``) and :343-350. Values: feature 1
    carries all four classes and an unrounded ``Class_0``; feature 2 is missing
    ``Class_3`` (a zone with no improved pixels); feature 3 is the ``LineString``
    that :353 drops.

The two ``reduceRegion`` payloads are the *unwrapped* dictionaries. The legacy read
the same content out of ``["features"][0]["properties"]["groups"]``, because it
wrapped the reduction in ``ee.Feature(None, ...)`` to get a ``getDownloadURL``
(:236-240, :284-289); awaiting the ``ee.Dictionary`` itself returns the properties
dict with no feature wrapper around it. The group lists are byte-identical either
way -- that is the whole of why the transport swap is safe (spec §7).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from sdg1531.scheme import LandCoverScheme

FIXTURES = Path(__file__).parent / "fixtures" / "stats"


def load_fixture(name: str) -> Any:
    return json.loads((FIXTURES / name).read_text())


class FakeResolved:
    """The subset of ResolvedSpec the stats layer reads.

    ``scheme``, ``lc_class_combinations``, ``lc_year_start_esa`` and
    ``lc_year_end_esa`` are what the decoders in this task read; the remaining
    three are the rest of the stats layer's surface and are here because Task 16's
    plots share this stub.
    """

    def __init__(self, *, start_year: int = 2001, end_year: int = 2015) -> None:
        self.scheme = LandCoverScheme.default()
        self.lc_class_combinations = tuple(self.scheme.class_combinations)
        self.lc_year_start_esa = start_year
        self.lc_year_end_esa = end_year
        self.lc_color_by_class = dict(self.scheme.color_by_class())
        self.analysis_scale = 300
        self.zonal_scale = 300
