"""Shared stubs for the stats tests.

Everything here is duck-typed on purpose: the decoders read four attributes off
the resolved spec and three members off the maps object, so the tests do not
need a full RunSpec/ResolvedSpec construction to exercise them.

Fixture provenance (tests/fixtures/stats/)
------------------------------------------
None of the three was produced by the code it now tests -- a fixture generated by
its own decoder proves nothing. They are hand-written payloads whose SHAPE is read
off the legacy consumers, which were themselves written against live Earth Engine
responses, and whose VALUES were chosen to exercise the decoders' edges:

``transition_areas.json``
    One flat group list. ``run_15_3_1.py:240-242`` reads ``g["lc_comb"]`` and
    ``g["sum"]`` off it, so each entry is keyed by the ``groupName`` passed to
    ``Reducer.group`` (``"lc_comb"``, :227) plus the ``"sum"`` of ``Reducer.sum``.
    Values: five transition codes drawn from the default seven-class vocabulary --
    a class onto itself (1010, 2020, 7070) and both directions of one off-diagonal
    pair (1030, 3010), so a decoder that read the code backwards would swap two
    rows rather than produce the same frame.

``areas_by_land_cover.json``
    The nested form the two stacked ``Reducer.group``s of :274 produce, outer key
    from ``.group(2, "indicator")`` and inner from ``.group(1, "lc")``.
    ``run_15_3_1.py:291-295`` reads exactly ``i["indicator"]``, ``i["groups"]``,
    ``g["lc"]`` and ``g["sum"]``. Values: three indicator classes over three land
    cover codes, deliberately RAGGED (2, 1 and 2 inner entries) so a decoder that
    assumed a rectangular payload would not survive, and with land cover 10 absent
    from indicator 3 so the pivot has a genuinely missing cell to fill.

``zonal_features.json``
    A GeoJSON FeatureCollection exactly as ``FeatureCollection.getInfo()`` returns
    one (run_15_3_1.py:544). The ``Class_N`` property spelling comes from
    ``ee.Number(...).format("Class_%d")`` at :519 and is confirmed by both legacy
    readers, :557 (``c.startswith("Class_")``) and :343-350. Values: feature 1
    carries all four classes and an unrounded ``Class_0``; feature 2 is missing
    ``Class_3`` (a zone with no improved pixels); feature 3 is the ``LineString``
    that :353 drops.

The two ``reduceRegion`` payloads are the *unwrapped* dictionaries. The legacy read
the same content out of ``["features"][0]["properties"]["groups"]``, because it
wrapped the reduction in ``ee.Feature(None, ...)`` to get a ``getDownloadURL``
(:236-240, :284-289); awaiting the ``ee.Dictionary`` itself returns the properties
dict with no feature wrapper around it. The group lists are byte-identical either
way -- that is the whole of why the transport swap is safe.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import ee

from sdg1531.engine.context import ExecutionContext
from sdg1531.enums import IndicatorLayer
from sdg1531.scheme import LandCoverScheme

FIXTURES = Path(__file__).parent / "fixtures" / "stats"


def load_fixture(name: str) -> Any:
    return json.loads((FIXTURES / name).read_text())


class FakeResolved:
    """The subset of ResolvedSpec the stats layer reads.

    ``scheme``, ``lc_class_combinations``, ``lc_year_start_esa`` and
    ``lc_year_end_esa`` are what the decoders in this task read; the remaining
    three are the rest of the stats layer's surface and are here because Task 16's
    plots share this stub.
    """

    def __init__(self, *, start_year: int = 2001, end_year: int = 2015) -> None:
        self.scheme = LandCoverScheme.default()
        self.lc_class_combinations = tuple(self.scheme.class_combinations)
        self.lc_year_start_esa = start_year
        self.lc_year_end_esa = end_year
        self.lc_color_by_class = dict(self.scheme.color_by_class())
        self.analysis_scale = 300
        self.zonal_scale = 300


class FakeFetcher:
    """An InfoFetcher that replays canned payloads.

    Proves the Protocol is satisfiable without importing pysepal. ``responses`` is
    consumed in call order; an entry that is an Exception instance is RETURNED, not
    raised - that is what pysepal's gee_interface.py:210 does, because it gathers
    with ``return_exceptions=True``. (Its single-call path re-raises instead, at
    :203-205; ``test_stats_api.py`` covers that shape too, with a fetcher that
    raises.)
    """

    def __init__(self, responses: list[Any]) -> None:
        self.responses = list(responses)
        self.calls: list[Any] = []

    async def get_info_async(self, ee_object: Any = None, tag: Any = None) -> Any:
        self.calls.append(ee_object)
        if not self.responses:
            raise AssertionError("FakeFetcher ran out of canned responses")
        return self.responses.pop(0)

    async def get_info_batch_async(self, ee_objects: list[Any]) -> list[Any]:
        return [await self.get_info_async(obj) for obj in ee_objects]


class StubLandCover:
    def __init__(self) -> None:
        # a DIFFERENT constant per band, so the serializer cannot merge two of them
        # and an assertion that a request read `transition` cannot be satisfied by a
        # graph that read `start` (tests/engine/test_indicator.py:85-90)
        self.stack = ee.Image.constant([1, 2, 3, 4, 5]).rename(
            ["degradation", "transition", "start", "end", "water"]
        )


class StubLayer:
    def __init__(self, image: ee.Image, band: str) -> None:
        self.image = image
        self.band = band


class StubMaps:
    """The three members the stats layer reads: ``resolved``, ``land_cover.stack``
    and ``layers()``.

    The trend and state images carry BOTH bands, exactly as the real ones do -- the
    5-level band the statistics select and the 3-class band the export selects. A
    stub that carried only one of them could not tell the two vocabularies apart.

    ``resolved`` defaults to ``None`` because the request builders must not read it;
    the api tests, whose decoders do, pass a :class:`FakeResolved`.
    """

    def __init__(self, resolved: Any = None) -> None:
        self.land_cover = StubLandCover()
        self.resolved = resolved
        self._layers = {
            IndicatorLayer.LAND_COVER: StubLayer(self.land_cover.stack, "degradation"),
            IndicatorLayer.SOC: StubLayer(ee.Image.constant(1).rename("soc"), "soc"),
            IndicatorLayer.PRODUCTIVITY: StubLayer(
                ee.Image.constant(2).rename("productivity"), "productivity"
            ),
            IndicatorLayer.PRODUCTIVITY_TREND: StubLayer(
                ee.Image.constant([1, 2]).rename(["trajectory_5_levels", "trajectory"]),
                "trajectory",
            ),
            IndicatorLayer.PRODUCTIVITY_STATE: StubLayer(
                ee.Image.constant([1, 2]).rename(["state_5_levels", "state"]), "state"
            ),
            IndicatorLayer.PRODUCTIVITY_PERFORMANCE: StubLayer(
                ee.Image.constant(1).rename("performance"), "performance"
            ),
            IndicatorLayer.INDICATOR_15_3_1: StubLayer(
                ee.Image.constant(3).rename("indicator_15_3_1"), "indicator_15_3_1"
            ),
        }

    def layers(self) -> dict[IndicatorLayer, StubLayer]:
        return dict(self._layers)


def make_ctx(scale: int = 300) -> ExecutionContext:
    """A live-collection context.

    ``tests/engine/conftest.py``'s ``ctx`` fixture is not reachable from a top-level
    test module, and the scale has to vary anyway -- a fixed one cannot tell
    ``ctx.analysis_scale`` from a hardcoded 300.
    """
    fc = ee.FeatureCollection([ee.Feature(ee.Geometry.Point([0, 0]).buffer(100))])
    return ExecutionContext.from_feature_collection(fc, scale)


def make_zones() -> ee.FeatureCollection:
    """A one-feature zone collection for the zonal request."""
    return ee.FeatureCollection([ee.Feature(ee.Geometry.Point([0, 0]).buffer(10))])
